server.port=8080

# ???? ?????? (???? ????????)
spring.datasource.url=jdbc:postgresql://ewm-db:5432/ewm
spring.datasource.username=ewm
spring.datasource.password=1234

# ????????? JPA ???? ??? entity
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always